version: '3'
services:
  torch_lab:
    build: .
    image: sangjeedondrub/torch_lab:v0.1
    container_name: sangjee_torch
    ports:
      - "10011:8888"
    env_file:
      - ./.docker.env
    volumes:
      - .:/workspace
    ipc: host
    restart: always

    environment:
      PYTHONIOENCODING: utf-8
      NVIDIA_VISIBLE_DEVICES: all
      LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
      PYTORCH_VERSION: v1.9.0

    command: ./entrypoint.sh
